### ISSUE TITLE
有些鉴定问题会出现如下报错

### ISSUE THREAD

**Issue by ankoconmf** [KroMiose/nonebot_plugin_dice_narrator#2]
08-26 00:14:11 [INFO] nonebot_plugin_dice_narrator | 请求消耗: 1443 tokens
08-26 00:14:11 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_dice_narrator.matchers, lineno=20) running complete
08-26 00:14:11 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_dice_narrator.matchers, lineno=20) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nonebot_plugin_dice_narrator\narrator.py", line 81, in run_narrator
    res_data = read_yml_str2data(content)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nonebot_plugin_dice_narrator\utils\common.py", line 15, in read_yml_str2data
    return yaml.safe_load(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 3, column 1:
    这是一个行为任务，成功的定义是玩家能够偷吃到午饭并且没有被发现。 ...
    ^
could not find expected ':'
  in "<unicode string>", line 5, column 1:
    success: 玩家成功地偷吃到了午饭，没有被任何人发现。他享 ...
    ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot\anko\bot.py", line 35, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nonebot_plugin_dice_narrator\matchers.py", line 51, in _
    await run_narrator(question=content[2:].strip(), matcher=matcher)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nonebot_plugin_dice_narrator\narrator.py", line 83, in run_narrator
    res_data = read_yml_str2data(content + "```")
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\nonebot_plugin_dice_narrator\utils\common.py", line 15, in read_yml_str2data
    return yaml.safe_load(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 3, column 1:
    这是一个行为任务，成功的定义是玩家能够偷吃到午饭并且没有被发现。 ...
    ^
could not find expected ':'
  in "<unicode string>", line 5, column 1:
    success: 玩家成功地偷吃到了午饭，没有被任何人发现。他享 ...
    ^

**Comment by KroMiose** [comment]
如果这个情况是随机发生的，大概率是因为ai返回了不标准的格式，导致无法解析结果，可以尝试更换更“聪明”的模型解决

**Comment by ankoconmf** [comment]
gpt-3.5-turbo也不行吗_(:з」∠)_，一开始还很好使，测试十几条都可以成功发送。现在十条有九条发不出来（

**Comment by KroMiose** [comment]
可以尝试先用3.5系列的老模型试试，可能是openai在新模型加了什么提示词导致写yml的能力下降了，错误能稳定复现吗？
